{
  "internalError": 1,
  "message": "No se ha podido encontrar el objeto"
}{
  "error": "Notificaci√≥n no encontrada"
}
